# TEMPORARY HARDCODED CONFIG FOR DEBUGGING
spring.datasource.url=jdbc:postgresql://db.thspagadcuvnasxtaewh.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Arpita2708A
spring.datasource.driver-class-name=org.postgresql.Driver

# Force Hibernate to use PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Ensure the port matches your Dockerfile
server.port=8085
